export interface Product {
    // para tornar o ID opcional deixe com id?:
    id?: any,
    name: string,
    classe: string,
    especie: string,
    langage: string,
    player: string,
    dinheiro: any,
    age?: any,
    xp: any,
    level: any,
    forca: any,
    resistencia: any,
    agilidade: any,
    persepcao: any,
    presisao: any,
    inteligencia: any,
    sopro: any,
    coragem: any,
    carisma: any,
    titulo: string,
    talento: string,
    aptidoes: string,
    ventura: any,
    vontade: any,
    estresse: any,
    medo: any,
    tendencia: any,
    status: any,
    dano: any,
    defesa: any,
    valorArmadura: any,
    valorArma: any,
    hitpoint: any,
}